### ISSUE TITLE
[PaaS-TA-PINPOINT-MONITORING-RELEASE] CCE issue

### ISSUE THREAD

**Issue by hsohans** [PaaS-TA/PAAS-TA-PINPOINT-MONITORING-RELEASE#1]
CCE 이슈 목록
|종류|호스트명|CCE-ID|점검항목|점검내용|
|------|---|---|--|--|
|pinpoint-monitoring|h_master|HA-01|파일 및 디렉토리 권한|퍼미션 적용|
|pinpoint-monitoring|h_master|HA-02|권한 관리|커버로스 인증 - keytab 파일|
|pinpoint-monitoring|h_master|HA-03|보안 설정|커버로스 설정|
|pinpoint-monitoring|h_master|HA-04|보안 설정|WebHDFS 설정|
|pinpoint-monitoring|h_master|HA-05|보안 설정|계정 및 그룹 설정|
|pinpoint-monitoring|h_master|HA-06|보안 설정|rpc 암호화 설정
|pinpoint-monitoring|h_master|HA-07|보안 설정|데이터 전송암호화 설정|
|pinpoint-monitoring|h_master|HA-08|패치 및 백업 관리|최신 버전 확인|
|pinpoint-monitoring|h_master|HA-09|패치 및 백업 관리|감사 로그 설정 확인|

**Comment by thouy** [comment]
According to Pinpoint official GitHub, Pinpoint not providing Kerberos authentication and no plan to provide it. (Related HA-02, HA-03)
ref.) https://github.com/pinpoint-apm/pinpoint/issues/3737

**Comment by thouy** [comment]
HA-02, HA-03, HA-07 are to be processed in the future
